### ISSUE TITLE
2 firmware

### ISSUE THREAD

**Issue by tokenpro1** [BlackTechX011/DeautherX#1]
what is different fimrware for??

**Comment by BlackTechX011** [comment]
> what is different fimrware for??

Bro one is for 1.3 inch OLED Display and other is for 0.96 inch OLED Display.
Now u don't need to download any flasher tool or any firmware just visit https://blacktechx011.github.io/DeautherX_Web_Tools/

**Comment by BlackTechX011** [comment]
Hope u understand

**Comment by BlackTechX011** [comment]
If u have any other issues feel free to contact me on telegram https://t.me/BlackTechX
