### ISSUE TITLE
issue #include <StringSplitter.h>

### ISSUE THREAD

**Issue by zenkiapo** [BlackTechX011/DeautherX#14]
C:\Users\zenkiapo\DeautherX\DeautherX\DeautherX.ino:1:28: fatal error: StringSplitter.h: No such file or directory
 #include <StringSplitter.h>
                            ^
compilation terminated.
exit status 1

Compilation error: StringSplitter.h: No such file or directory

**Comment by NetviperZ** [comment]
Install the Missing Library:

Go to Sketch > Include Library > Manage Libraries > search for "StringSplitter"
