### ISSUE TITLE
Failed to download manifest

### ISSUE THREAD

**Issue by Neutrale35** [BlackTechX011/DeautherX#2]
when i click on the connect button on the web site, it can see my com port and successfully connect but says failed to download manifest on chrome. edge says also same thing. and when i tried to install board on ide, it says Failed to install platform: 'DeautherX ESP8266 Boards:2.0.0'. 9 FAILED_PRECONDITION: Platform 'deautherx:esp8266@2.0.0' not found: getting tool dependencies for platform deautherx:esp8266@2.0.0: package deauther not found.

**Comment by BlackTechX011** [comment]
Thank You for your feedback.
 [DeautherX web tools](https://blacktechx011.github.io/DeautherX_Web_Tools/) will be updated soon.

**Comment by BlackTechX011** [comment]
can you provide more information about what exactly happened with initialisation with Arduino IDE.
you can contact me on telegram https://t.me/BlackTechX

**Comment by BlackTechX011** [comment]
Thank You @Neutrale35. DeautherX Web Tools has been updated

**Comment by Neutrale35** [comment]
> Thank You @Neutrale35. DeautherX Web Tools has been updated

I tried it and works well for me. Thanks for your time ✌🏼

**Comment by GordoCodo** [comment]
I'm experiencing the same issue adding the board via the board manager in Arduino IDE that @Neutrale35  did.

"Failed to install platform: 'DeautherX ESP8266 Boards:2.1.1'. 9 FAILED_PRECONDITION: Platform 'deautherx:esp8266@2.1.1' not found: getting tool dependencies for platform deautherx:esp8266@2.1.1: package deauther not found"

Any chance you could take another look @BlackTechX011 ?

**Comment by BlackTechX011** [comment]
# @GordoCodo
___
Thank you for feedback
___
I will fix it soon
___
