### ISSUE TITLE
ets Jan  8 2013,rst cause:4, boot mode:(3,6)

### ISSUE THREAD

**Issue by xrayotix** [BlackTechX011/DeautherX#4]
I tried to flash the firmware to the esp8266 with your webtool but my esp keeps resetting/rebooting. do you have a solution?

[esp-web-tools-logs (1).txt](https://github.com/BlackTechX011/DeautherX/files/14374936/esp-web-tools-logs.1.txt)

**Comment by BlackTechX011** [comment]
okay just flash esp with Arduino ide.

**Comment by BlackTechX011** [comment]
or contact me on telegram t.me/BlackTechX

**Comment by xrayotix** [comment]
> okay just flash esp with Arduino ide.

i have already try with arduino ide too but im still facing the same problem ![IMG_20240224_100711.jpg](https://github.com/BlackTechX011/DeautherX/assets/138425849/6df2ec63-d3a1-4e70-a723-91199a886076)

**Comment by BlackTechX011** [comment]
please contact me on telegram t.me/BlackTechX so i can help u out

**Comment by BDhackers009** [comment]
I got the same issue in i trried the web flasher also tried arduino ide but the same problem resetting/rebooting. Also I could not find the telegram username it doesnt exist.

![image](https://github.com/BlackTechX011/DeautherX/assets/67186139/eaafa972-3493-4223-aa99-34ef8f480a67)

**Comment by BlackTechX011** [comment]
# DeautherX
## BlackTechX
### Issues
esp keeps rebooting
### Fixed
Now don't worry I have fixed it.
