### ISSUE TITLE
Captured Wi-Fi passwords not saving.

### ISSUE THREAD

**Issue by BDhackers009** [BlackTechX011/DeautherX#7]
Thanks for the tool sir. I am trying yo use the evil twin option. It creates a fake ap and after entering the password on the phishing page i can't seem to find the password. Where do i find the password which the victim entered. Any info will help.

**Comment by BlackTechX011** [comment]
# @BDhackers009 
After the target enters the correct password for their AP, the evil twin password will become visible. It will appear in the 'FS' tab of the web interface, and on the display, it will be shown in the evil twin menu.
