### ISSUE TITLE
Wifi Range Is Too Low

### ISSUE THREAD

**Issue by ridwan4200** [BlackTechX011/DeautherX#9]
I have Used This Programe In Nodemcu Using Button And oled Display and Have seen that tge range of wifi is low and it caught maximum 5 access points of wifi but in my phone my wifi show there are around 10-15 wifi's
Author I want you To fix This Issue

**Comment by BlackTechX011** [comment]
try by adding antenna or contact me on telegram https://t.me/@BlackTechX011
